### ISSUE TITLE
No longer works with Apple TestFlight?

### ISSUE THREAD

**Issue by micnguyen** [infolens/CircleCI-iOS-TestFlight-Sample#7]
Now that Testflight has been purchased by Apple, does the current uploading to testflightapp.com still work? I'm looking at the builds on CircleCI and it doesn't seem like it.

**Comment by thorikawa** [comment]
Apple testflight is completely different from the old one, so it does not work. Please consider using similar services with old one, like hockey app or beta by crashlytics for which you just need to slightly modify the upload script.
